/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GCP_BLAST_LIB */

#ifndef _Included_GCP_BLAST_LIB
#define _Included_GCP_BLAST_LIB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GCP_BLAST_LIB
 * Method:    prelim_search
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_GCP_1BLAST_1LIB_prelim_1search
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     GCP_BLAST_LIB
 * Method:    traceback
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_GCP_1BLAST_1LIB_traceback
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
