/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BlastJNI */

#ifndef _Included_BlastJNI
#define _Included_BlastJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BlastJNI
 * Method:    prelim_search
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_BlastJNI_prelim_1search
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
