/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_nih_nlm_ncbi_blastjni_BlastJNI */

#ifndef _Included_gov_nih_nlm_ncbi_blastjni_BlastJNI
#define _Included_gov_nih_nlm_ncbi_blastjni_BlastJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_nih_nlm_ncbi_blastjni_BlastJNI
 * Method:    prelim_search
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_gov_nih_nlm_ncbi_blastjni_BlastJNI_prelim_1search
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/*
vartanianmh
javac 1.8.0_131
g++ (Debian 4.9.2-10+deb8u1) 4.9.2
Wed Mar 14 20:01:17 UTC 2018
*/
