/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_nih_nlm_ncbi_blastjni_BLAST_LIB */

#ifndef _Included_gov_nih_nlm_ncbi_blastjni_BLAST_LIB
#define _Included_gov_nih_nlm_ncbi_blastjni_BLAST_LIB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_nih_nlm_ncbi_blastjni_BLAST_LIB
 * Method:    prelim_search
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)[Lgov/nih/nlm/ncbi/blastjni/BLAST_HSP_LIST;
 */
JNIEXPORT jobjectArray JNICALL Java_gov_nih_nlm_ncbi_blastjni_BLAST_1LIB_prelim_1search
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     gov_nih_nlm_ncbi_blastjni_BLAST_LIB
 * Method:    traceback
 * Signature: ([Lgov/nih/nlm/ncbi/blastjni/BLAST_HSP_LIST;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Lgov/nih/nlm/ncbi/blastjni/BLAST_TB_LIST;
 */
JNIEXPORT jobjectArray JNICALL Java_gov_nih_nlm_ncbi_blastjni_BLAST_1LIB_traceback
  (JNIEnv *, jobject, jobjectArray, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
